`ifndef TB_CONFIG_SVH
`define TB_CONFIG_SVH

`define BIT_WIDTH        8
`define PIXELS_PER_BEAT  16
`define IMAGE_WIDTH      512

`define S_AXIS_DATA_WIDTH  (`BIT_WIDTH * `PIXELS_PER_BEAT)   // 128
`define M_AXIS_DATA_WIDTH  (`BIT_WIDTH * `PIXELS_PER_BEAT)   // 128

`define S_AXIS_TOTAL_BEATS (`IMAGE_WIDTH * `IMAGE_WIDTH / `PIXELS_PER_BEAT)
`define M_AXIS_TOTAL_BEATS (`IMAGE_WIDTH * `IMAGE_WIDTH / `PIXELS_PER_BEAT)

`endif