#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Aug 05 19:05:33 IST 2026
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_top_behav -key {Behavioral:sim_1:Functional:tb_top} -tclbatch tb_top.tcl -log simulate.log -testplusarg IN_FILE_NAME=/home/23EC01052/Desktop/my_branch/LRF/workspace/conv_sobel_random/inputs.hex -testplusarg OUT_FILE_NAME=/home/23EC01052/Desktop/my_branch/LRF/workspace/conv_sobel_random/outputs.hex"
xsim tb_top_behav -key {Behavioral:sim_1:Functional:tb_top} -tclbatch tb_top.tcl -log simulate.log -testplusarg IN_FILE_NAME=/home/23EC01052/Desktop/my_branch/LRF/workspace/conv_sobel_random/inputs.hex -testplusarg OUT_FILE_NAME=/home/23EC01052/Desktop/my_branch/LRF/workspace/conv_sobel_random/outputs.hex

